rafael_santiago_spotify_login:
    path:     /login
    defaults: { _controller: RafaelSantiagoSpotifyBundle:Spotify:login }

rafael_santiago_spotify_login_return:
    path:     /login/return
    defaults: { _controller: RafaelSantiagoSpotifyBundle:Spotify:loginReturn }

rafael_santiago_spotify_playlists:
    path:     /playlists
    defaults: { _controller: RafaelSantiagoSpotifyBundle:Spotify:playlists }

rafael_santiago_spotify_playlist_detail:
    path:     /playlists/{owner_id}/{list_id}
    defaults: { _controller: RafaelSantiagoSpotifyBundle:Spotify:playlistDetail }